name: test
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: macos-10.15
    steps:
#       - name: set-node-type
#         run: echo "NODE_TYPE=tg4.small" >> $GITHUB_ENV
#         if: ${{ matrix.provider == 'aws-arm64' }}
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.12'
      - name: curl
        run: curl -L https://github.com/convox/convox/releases/download/test-k8s-1.19/convox-macos -o /tmp/convox && chmod +x /tmp/convox
      - name: convox
        run: /tmp/convox
