name: test
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
#       - name: set-node-type
#         run: echo "NODE_TYPE=tg4.small" >> $GITHUB_ENV
#         if: ${{ matrix.provider == 'aws-arm64' }}
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.12'
      - name: goversion
        run: go version
      - name: goenv
        run: go env
