name: test
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        provider:
          - aws
          - aws-arm64
    steps:
      - name: set-node-type
        run: echo "NODE_TYPE=tg4.small" >> $GITHUB_ENV
        if: ${{ matrix.provider }} == "aws-arm64"
      - name: install
        run: echo "install ${PROVIDER} ${NODE_TYPE}""
